fos_rest:
  param_fetcher_listener:  true
  body_listener: true
  format_listener:
    enabled: true
    rules:
    - { path: '^/api', prefer_extension: true, fallback_format: json }
    - { path: '^/', prefer_extension: true, fallback_format: html }
